name: build workflow

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  SOLUTION_DIRECTORY : src
  SOLUTION_PATH : src/FluentSetups.sln
  ON_MASTER_BRANCH : ${{ github.ref == 'refs/heads/master' }} 
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: should publish   
      run: echo ON_MASTER_BRANCH = ${{ env.ON_MASTER_BRANCH }}

    - name: checkout branch
      uses: actions/checkout@v3

    - name: setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.6
      with:
        nuget-version: latest
        nuget-api-key: ${{secrets.NUGET_API_KEY}}
    
    - name: restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_PATH }}
    
    - name: setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: build solution
      run: msbuild ${{ env.SOLUTION_PATH }} -property:Configuration=Release
   
    - name: setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1
      
      #TODO create matrix for all platforms
    - name: run unit tests
      run: vstest.console.exe ${{ env.SOLUTION_DIRECTORY }}\Release\net6.0\FluentSetups.UnitTests.dll

    - name: upload artifacts
      if: ${{ env.ON_MASTER_BRANCH }}
      uses: actions/upload-artifact@v3.0.0
      with:
        name: nugetPackage
        path: src\Release\*.nupkg
        retention-days: 1

  publish:
    needs: build
    runs-on: windows-latest
    if: ${{ env.ON_MASTER_BRANCH }}
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v3.0.0
      with:
        name: nugetPackage
        path: packages
        
    - name: show packages
      run: dir packages
      
    - name: push to nuget.org
      run: nuget push packages\*.nupkg -src https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }} -SkipDuplicate
  
