name: Build and Test FluentSetups

on:
  push:
    branches: [ master ]
    #paths-ignore:
    #   - '**.yml'
  pull_request:
    branches: [ master ]
  # this allowes running the workflow manualy on git hub 
  workflow_dispatch:

env:
  SOLUTION_PATH : src/FluentSetups.sln


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout branch
      uses: actions/checkout@v3
    
    - name: setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.6
      with:
        nuget-version: latest
        nuget-api-key: ${{secrets.NUGET_API_KEY}}

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: restore NuGet packages
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: build solution
      run: msbuild ${{ env.SOLUTION_PATH }} -property:Configuration=Release
   
    - name: setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: nugetPackage
        path: src\Release\*.nupkg
        warn: the nuget package could not be found
        retention-days: 1
      
    - name: push to nuget.org
      run: nuget push src\Release\*.nupkg -src https://api.nuget.org/v3/index.json -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
  
  
