name: Build and Test

on:
  push:
    branches-ignore: [ master ]
    # paths-ignore:
    #  - '**.yml'
  pull_request:
    branches-ignore: [ master ]
  workflow_dispatch:

env:
  SOLUTION_DIRECTORY : src
  SOLUTION_PATH : src/FluentSetups.sln
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: check branch
      if: github.ref != 'refs/heads/master'  
      run: echo we are not on master

    - name: checkout branch
      uses: actions/checkout@v3

    - name: setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.6
      with:
        nuget-version: latest
        nuget-api-key: ${{secrets.NUGET_API_KEY}}
    
    - name: restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_PATH }}
    
    - name: setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: build solution
      run: msbuild ${{ env.SOLUTION_PATH }} -property:Configuration=Release
   
    - name: setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1
      
      #TODO create matrix for all platforms
    - name: run unit tests
      run: vstest.console.exe ${{ env.SOLUTION_DIRECTORY }}\Release\net6.0\FluentSetups.UnitTests.dll

    - name: upload artifacts
      #if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v3.0.0
      with:
        name: nugetPackage
        path: src\Release\*.nupkg
        retention-days: 1

  publish:
    needs: build
    runs-on: windows-latest
    #if: github.ref == 'refs/heads/master'
    steps:
    - name: download nuget
      if: github.ref == 'refs/heads/master'
      uses: actions/download-artifact@v3.0.0
      with:
        name: nugetPackage
        path: downloads
        
    - name: show download
      run: dir downloads
  
