name: pass files

on:
  push:
    branches-ignore: [ master ]
  workflow_dispatch:

jobs:
  create-file:
    runs-on: windows-latest

    steps:
    - name: create file
      run: echo FromJob1  > theFile.txt
    - name: create anoter file
      run: echo otherContent  > secons.txt

    - name: dir
      run: dir

    - name: mkdir direc
      run: mkdir direc

    - name: cd direc
      run: cd direc

    - name: create anoter file
      run: echo otherContent  > secons.txt

    - name: Cache file
      uses: actions/cache@v3
      with:
        path: theFile.txt
        key:  ${{ runner.os }}-FluentSetups-${{ hashFiles('**/*.txt') }}
        restore-keys: ${{ runner.os }}-FluentSetup


# Now comes another machine

  use-file:
    needs: create-file
    runs-on: windows-latest

    steps:
    - name: open file
      run: dir

    - name: Cache file
      uses: actions/cache@v3
      with:
        path: theFile.txt
        restore-keys: ${{ runner.os }}-FluentSetup

    - name: open file
      run: dir

  
