name: please work

on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: windows-latest

    steps:
    - name: create file
      run: echo FromJob1  > theFile.txt
      
  use-file:
    needs: create-file
    runs-on: windows-latest

    steps:
    - name: open file
      run: dir


  
