name: pass files

on:
  push:
    branches-ignore: [ master ]
  workflow_dispatch:

jobs:
  create-file:
    runs-on: windows-latest

    steps:
    - name: create file
      run: echo FromJob1  > theFile.txt

    - name: dir
      run: dir

    - name: Cache file
      uses: actions/cache@v3
      with:
        path: theFile.txt
        key:  thisIsTheKey


# Now comes another machine

  use-file:
    needs: create-file
    runs-on: windows-latest

    steps:
    - name: open file
      run: dir

    - name: Cache file
      uses: actions/cache@v3
      with:
        path: theFile.txt
        key:  thisIsTheKey

    - name: open file
      run: dir

  
